version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: api2
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
